### ISSUE TITLE
Allow parameters to pam_access

### ISSUE THREAD

**Issue by glorang** [authselect/authselect#235] opened 2021-02-04 14:37 UTC
Hello, 

When integrating systems with Active Directory via winbind + pam_access we must be able to set pam_access's `listsep` parameter as it is in Microsoft's / AD's nature to have group names with spaces.

For now we're doing `authselect select winbind with-mkhomedir with-pamaccess` and updating `password-auth` and `system-auth` manually to `account     required                                     pam_access.so listsep=','` but it would be better if we can set it via authselect.

There are more parameters that might need to be included, e.g. accessfile. (_pam_access.so [debug] [nodefgroup] [noaudit] [accessfile=file] [fieldsep=sep] [listsep=sep]_)

PS: the links in README under Contribution > Issues | Pull request link to pbrezina's repo instead of this one

Thanks,
Geert

**Comment by pbrezina** [comment] 2021-02-05 11:39
I would rather like to see these options supported in `/etc/security/access.conf` to avoid modification of the PAM stack. Would you mind reporting the issue on https://github.com/linux-pam/linux-pam/issues or even RHBZ where I could get it more traction?

**Comment by pbrezina** [comment] 2021-02-05 11:42
> PS: the links in README under Contribution > Issues | Pull request link to pbrezina's repo instead of this one

Thank you, this is now fixed.

**Comment by glorang** [comment] 2021-02-05 23:43
Using `access.conf` would introduce a circular dependency so not sure that's the best option but I've logged bug #1925718 @ RHBZ.

**Comment by pbrezina** [comment] 2021-02-18 09:08
Thank you. Lets see what we can do in the module itself. But from authselect perspective - authselect does not allow to set user values by design. If you need to provide custom values to some attribute, please create a [custom profile](https://github.com/authselect/authselect/wiki/How-To:-Create-new-profile) that is based on the one you use right now.

**Comment by pbrezina** [comment] 2021-03-31 10:15
This will be done in pam_access, tracked by https://bugzilla.redhat.com/show_bug.cgi?id=1925718

**Closed by pbrezina** 2021-03-31 10:15 UTC
