### ISSUE TITLE
Don't use "nouserok" for "with-pam-u2f-2fa"

### ISSUE THREAD

**Issue by dlippold** [authselect/authselect#217] opened 2020-07-07 12:56 UTC
When one uses "with-pam-u2f-2fa" one want to force two factor authentication. But because authselect adds the option "nouserok" to "pam_u2f" in the files "/etcpam.d/*" every user can disable two factor authentication by removing its authfile. Therefore "nouserok" should not be added if "with-pam-u2f-2fa" is used.

authselect should check that root has an authfile before executing the command because root could not login anymore after the change if root has no authfile.

In addition an option "with-nouserok" could be added to authselect so that "authselect select sssd with-pam-u2f-2fa with-nouserok" has the same effect as the current default.

**Comment by pbrezina** [comment] 2020-07-29 10:11
Thank you. I'm going to close this as a duplicate of https://github.com/authselect/authselect/issues/216

**Closed by pbrezina** 2020-07-29 10:11 UTC
Labels: duplicate
